[project]
dependencies = [
  "lmnr>=0.5.2",
]
description = "Add your description here"
name = "eval-ts"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[tool.uv.sources]
lmnr = {path = "../lmnr-python-sdk"}
