[project]
dependencies = [
  "lmnr @ git+https://github.com/lmnr-ai/lmnr-python.git@stop-bg-events",
]
description = "Add your description here"
name = "eval-ts"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"
