name: Run Python Test eval
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  eval-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install the dependencies
        run: python -m pip install --upgrade pip && python -m pip install .
      - name: Run eval
        uses: ./
        with:
          language: python
          lmnr-project-api-key: ${{ secrets.LMNR_PROJECT_API_KEY }}
